swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: API to manage bank account informations
  version: 1.0.0
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http

paths:
  /accounts:
    get:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: Retrieve all account information
      description: API to retrieve all account information
      produces:
        - application/json
      responses:
        "200":
          description: Successful retrieval of account information
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error

  /accounts/{accountId}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get transactions for a specific account
      parameters:
        - name: accountId
          in: path
          description: Account ID
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Transactions retrieved successfully
          schema:
            type: array
            items:
              $ref: "#/definitions/Transaction"
        "401":
          description: Unauthorized
        "404":
          description: No transaction found
        "500":
          description: Internal Server Error

  /accounts/{accountId}/transactions/{transactionId}/category:
    put:
      security:
        - Bearer: []
      tags:
        - Category Module
      summary: Update transaction category
      description: API to update transaction category
      parameters:
        - name: accountId
          in: path
          required: true
          type: string
          description: ID of the account
        - name: transactionId
          in: path
          required: true
          type: string
          description: ID of the transaction
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              category:
                type: string
                example: "New category"
      produces:
        - application/json
      responses:
        "200":
          description: Successful update of transaction category
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error

  /accounts/{accountId}/transactions/{transactionId}/note:
    post:
      security:
        - Bearer: []
      tags:
        - Note Module
      summary: Create a note for a transaction
      description: API to create a note for a transaction
      parameters:
        - name: accountId
          in: path
          required: true
          type: string
          description: ID of the account
        - name: transactionId
          in: path
          required: true
          type: string
          description: ID of the transaction
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              note:
                type: string
                example: "This is a new note"
      produces:
        - application/json
      responses:
        "201":
          description: Note created successfully
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error

    delete:
      security:
        - Bearer: []
      tags:
        - Note Module
      summary: Delete a note for a transaction
      description: API to delete a note for a transaction
      parameters:
        - name: accountId
          in: path
          required: true
          type: string
          description: ID of the account
        - name: transactionId
          in: path
          required: true
          type: string
          description: ID of the transaction
       
      produces:
        - application/json
      responses:
        "200":
          description: Note deleted successfully
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error

    put:
      security:
        - Bearer: []
      tags:
        - Note Module
      summary: Update a note for a transaction
      description: API to update a note for a transaction
      parameters:
        - name: accountId
          in: path
          required: true
          type: string
          description: ID of the account
        - name: transactionId
          in: path
          required: true
          type: string
          description: ID of the transaction
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              note:
                type: string
                example: "Updated note content"
      produces:
        - application/json
      responses:
        "200":
          description: Note updated successfully
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string

  Account:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      accountNumber:
        type: string
      balance:
        type: number
        format: float
      typeAccount:
        type: string

  Transaction:
    type: object
    properties:
      id:
        type: integer
      description:
        type: string
      amount:
        type: number
        format: float
      date:
        type: string
        format: date
      balance:
        type: number
        format: float
      transactionType:
        type: string
      note:
        type: string
      category:
        type: string

  Category:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string